name: food_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  flutter:
    sdk: flutter
  http: ^1.3.0
  google_fonts: ^6.2.1
  dots_indicator: ^3.0.0
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/restaurantdupe.png
  - assets/images/japanese.jpg
  - assets/images/drink.png
  - assets/images/dessert.png
  - assets/images/profile.jpg
  - assets/images/menusushione.png
  - assets/images/menusushitwo.png
  - assets/images/menusushithree.png
  - assets/images/menusushifour.png
  - assets/images/menusushifive.png
  - assets/images/menuorange.png
  - assets/images/cupcakeblueberry.png
  - assets/images/cupcakebanana.png
  - assets/images/cupcakestrawberry.png
  - assets/images/cupcakegrapemint.png
  - assets/images/suggestedrestaurantone.png
  - assets/images/suggestedrestauranttwo.png
  - assets/images/kimbap.png